Name_1=(input("Enter a name"))
Verb_1=(input("Enter your first verb:"))
Verb_2=(input("Enter your second verb:"))
Noun_1=(input("Enter a plural noun:"))
Noun_2=(input("Enter a noun:"))
Color_1=(input("Enter a color:"))
Number_1=int(input("Enter a whole number:#"))
Celeberty_guest=(input("Enter the name of a celeberty:"))

Madlib=(f"{Name_1}, you have been chosen for the great butter contest. Please {Verb_1} through the butter before your competiors do. Yet it felt like I was {Verb_2} through the snow instead! As I continued my journey I saw {Celeberty_guest}! They were wearing {Noun_2} and walking on {Number_1} {Color_1} {Noun_1}!")
print(f"Madlib:{Madlib}")