Verb_1=(input("Enter your first verb:"))
Verb_2=(input("Enter your second verb:"))
Noun_1=(input("Enter a plural noun:"))
Noun_2=(input("Enter a noun:"))
Color_1=(input("Enter a color:"))
Number_1=int(input("Enter a whole number:#"))
Celeberty_guest=(input("Enter the name of a celeberty:"))
